version: 2

project_name: gasadd

builds:
  - binary: ga
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

brews:
  - repository:
      owner: nmelo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/nmelo/gasadd
    description: Queue messages to Claude agents in tmux windows without interrupting
    license: MIT
    install: |
      bin.install "ga"
